ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "E:/Dev/learn_python/test_exception.py", line 9, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "E:/Dev/learn_python/test_exception.py", line 9, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "E:/Dev/learn_python/test_exception.py", line 10, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "E:/Dev/learn_python/test_exception.py", line 10, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "E:/Dev/learn_python/test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
ERROR:__main__:invalid literal for int() with base 10: 'A/N'
Traceback (most recent call last):
  File "test_exception.py", line 11, in test
    int('A/N')
ValueError: invalid literal for int() with base 10: 'A/N'
